# Generated by Django 4.0.2 on 2024-12-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformedcompanydata',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='transformedcompanydata',
            name='days_open',
        ),
        migrations.RemoveField(
            model_name='transformedcompanydata',
            name='hours_open',
        ),
        migrations.AddField(
            model_name='transformedcompanydata',
            name='data',
            field=models.TextField(default='2024-01-01 12:45:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformedcompanydata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:12:12'),
            preserve_default=False,
        ),
    ]
