# Generated by Django 4.0.2 on 2024-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woapi', '0002_remove_transformedcompanydata_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformedcompanydata',
            old_name='data',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='transformedcompanydata',
            name='close',
            field=models.TimeField(default='20:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformedcompanydata',
            name='day',
            field=models.TextField(default='Monday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformedcompanydata',
            name='open',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
    ]
