# Generated by Django 4.0.2 on 2024-12-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woapi', '0004_remove_transformedcompanydata_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformedcompanydata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 09:00:00'),
            preserve_default=False,
        ),
    ]
