# Generated by Django 4.0.2 on 2024-12-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woapi', '0005_transformedcompanydata_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformedcompanydata',
            name='timestamp',
        ),
    ]
