# Generated by Django 4.0.2 on 2024-12-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woapi', '0006_remove_transformedcompanydata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTransformedCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
            ],
        ),
    ]
