# Generated by Django 4.0.2 on 2024-12-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woapi', '0008_delete_ttransformedcompanydata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformedcompanydata',
            name='company_name',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
