# Generated by Django 4.0.2 on 2024-12-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woapi', '0009_transformedcompanydata_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformedcompanydata',
            name='open',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
