# Generated by Django 4.0.2 on 2024-12-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woapi', '0010_transformedcompanydata_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformedcompanydata',
            name='data',
        ),
        migrations.AddField(
            model_name='transformedcompanydata',
            name='close',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformedcompanydata',
            name='day',
            field=models.TextField(default='Monday'),
            preserve_default=False,
        ),
    ]
