# Generated by Django 5.1.4 on 2024-12-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woapi', '0011_remove_transformedcompanydata_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformedcompanydata',
            old_name='day',
            new_name='wkday',
        ),
    ]
